### ISSUE TITLE
No readme and yet doesnt work when upgrading ember-data

### ISSUE THREAD

**Issue by brendanoh** [emberjs/ember-data-fixture-adapter#7]
I use fixtures to represent models that have not been added to the DB yet so I can't use restAdapter. 

Upgraded to latest ED and then fixtures stopped working. Installed this addon and still not working. 

```
import DS from 'ember-data';

export default DS.FixtureAdapter;
```

```
TypeError: serializer.get is not a function
    at ember$data$lib$system$store$serializer$response$$normalizeResponseHelper (serializer-response.js:42)
```

For anyone using Fixtures and upgrading to latest ED it is a total blocker with no info on how to fix.

**Comment by brendanoh** [comment]
"ember": "1.11.3",
    "ember-data": "1.13.4",

**Comment by brendanoh** [comment]
Maybe cause I am importing from the wrong place or maybe because the install failed (although was added to package.json and node_modules folder):
```
➜  mgmt-castle git:(feat/brendan/material-design) ✗ ember install ember-data-fixture-adapter
version: 0.2.7
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/brendan/Documents/sr/mgmt-castle/node_modules/ember-cli/lib/models/project.js:482:53
    at baseFindIndex (/Users/brendan/Documents/sr/mgmt-castle/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /Users/brendan/Documents/sr/mgmt-castle/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/Users/brendan/Documents/sr/mgmt-castle/node_modules/ember-cli/lib/models/project.js:481:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/Users/brendan/Documents/sr/mgmt-castle/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
    at Class.module.exports.Task.extend.installBlueprint (/Users/brendan/Documents/sr/mgmt-castle/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
    at Class.<anonymous> (/Users/brendan/Documents/sr/mgmt-castle/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/Users/brendan/Documents/sr/mgmt-castle/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/brendan/Documents/sr/mgmt-castle/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/brendan/Documents/sr/mgmt-castle/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
```

**Comment by stefanpenner** [comment]
a repository demonstrating the issue would make it nice and actionable for potential contributors.

**Comment by stefanpenner** [comment]
the last part feels fishy

**Comment by stefanpenner** [comment]
example repo that seems to work correctly: https://github.com/stefanpenner/___ember-data-fixture-adapter-example

**Comment by brendanoh** [comment]
Will do. Thanks for this. 

Tried nombom-ing and that died too.

Will try to adjust your repo to see if my use case still fails.

**Comment by stefanpenner** [comment]
I have slightly updated the repo.

Unfortunately when running the tests I have realized that many things feel foobar'd. Mostly so far it has to do with the test setup itself. I am going to see if I can get the tests back into working shape.

**Comment by brendanoh** [comment]
Your repo is ed beta 18 which still has the F-Adapter in it I believe. Also Ember 12 when I am on 1.11.3. 

Also, I have an application adapter that is activeModel and have named adapters for fixtures. Will pull your latest and try to see what works / doesnt.

Thanks again

**Comment by brendanoh** [comment]
I adjusted to my situation and get the same error. Will post a PR momentarily.

**Comment by stefanpenner** [comment]
holy tests using private API's batman

**Comment by brendanoh** [comment]
https://github.com/stefanpenner/___ember-data-fixture-adapter-example/pull/1/files

Error is the same as my SimpleReach repo. 

```
TypeError: serializer.get is not a function
    at ember$data$lib$system$store$serializer$response$$normalizeResponseHelper (serializer-response.js:42)
    at finders.js:150
    at Object.Backburner.run (ember.debug.js:217)
    at ember$data$lib$system$store$$Service.extend._adapterRun (store.js:1958)
    at finders.js:149
    at tryCatch (ember.debug.js:46977)
    at invokeCallback (ember.debug.js:46989)
    at publish (ember.debug.js:46960)
    at ember.debug.js:27293
    at Queue.invoke (ember.debug.js:871)onerrorDefault @ ember.debug.js:27332__exports__.default.trigger @ ember.debug.js:47656Promise._onerror @ ember.debug.js:48668publishRejection @ ember.debug.js:46899(anonymous function) @ ember.debug.js:27293Queue.invoke @ ember.debug.js:871Queue.flush @ ember.debug.js:936DeferredActionQueues.flush @ ember.debug.js:741Backburner.end @ ember.debug.js:166Backburner.run @ ember.debug.js:221executeTimers @ ember.debug.js:603(anonymous function)
```

**Comment by brendanoh** [comment]
It just seems to not recognize named adapters if there is an application adapter.

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember-data-fixture-adapter/pull/8

**Comment by stefanpenner** [comment]
repo demonstrating (thanks @brendanoh) https://github.com/stefanpenner/___ember-data-fixture-adapter-example/pull/1

**Comment by stefanpenner** [comment]
Also i did add a small readme addition. Editing your issue to convey this.

**Comment by stefanpenner** [comment]
should be fixed by https://github.com/emberjs/ember-data-fixture-adapter/pull/9 please confirm

**Comment by ryrych** [comment]
@stefanpenner https://github.com/emberjs/ember-data-fixture-adapter/issues/10

Can't make it work. I cleaned bower & npm cache and tried to install again with no success.

**Comment by rwjblue** [comment]
Sorry that you are running into issues, this repo / project is essentially deprecated and unmaintained. 

I'm closing this (so that I can archive the repo and make it clearer to folks that this shouldn't be used going forward)...
